/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:af91124d-13b4-4260-aad4-cdf3ff9c2d5e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ePUHRaQa8",
    "aws_user_pools_web_client_id": "6hhv7eq69g43np05ki92r7q3b1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://a2w2vsspojbl3habfua4zxckxq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
